### ISSUE TITLE
Saving java.util.Date does not work properly

### ISSUE THREAD

**Issue by mucki1987** [mhus-info/mhus-reactive#7]
Saving java.util.Date Date does not work properly.

I tried setting a new Date in my Date variable:
`
@PropertyDescription(initial = true)
private Date case_startDate;

public void setCase_startDate(Date case_startDate) {
        this.case_startDate = case_startDate;
}

setCase_startDate(new Date());
`

After several nodes i tried using it via pool:
`
NumberCreatePool pool = getContext().getPool();
pool.getCase_startDate();
`
and that is null.

Can you please verify this error and try to fix it. thx :)

**Comment by mhus** [comment]
Duplicates #8
